/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package audioplayer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AudioPlayerTest {
   // @Test void appHasAGreeting() {
   //     Main classUnderTest = new Main();
   //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
   // }
}
